services:
    ukm_delta.season:
        class: UKMNorge\DeltaBundle\Services\SeasonService
#    ukm_delta.example:
#        class: UKMNorge\DeltaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]