services:
    ukm_delta.season:
        class: UKMNorge\DeltaBundle\Services\SeasonService
        arguments: [@service_container]
    ukm_delta.menu:
        class: UKMNorge\DeltaBundle\Services\MenuService
        arguments: [@service_container, @ukmdesign.sitemap]
#    ukm_delta.example:
#        class: UKMNorge\DeltaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]