services:
    ukm_api.person:
        class: UKMNorge\APIBundle\Services\PersonService
        arguments: ['@service_container']
    ukm_api.innslag:
        class: UKMNorge\APIBundle\Services\InnslagService
        arguments: ['@service_container']
    ukm_api.arrangement:
        class: UKMNorge\APIBundle\Services\ArrangementService
        arguments: ['@service_container']
    ukm_api.geografi:
        class: UKMNorge\APIBundle\Services\GeografiService
        arguments: ['@service_container']
#    ukmapi.example:
#        class: UKMNorge\APIBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
